import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useLocation, useNavigate } from "react-router-dom";
import "./Confirmation.css";
export default function Confirmation() {
    const nav = useNavigate();
    const { state } = useLocation();
    const data = state;
    if (!data) {
        return (_jsx("div", { className: "confirm-page", children: _jsxs("div", { className: "confirm-card", children: [_jsx("div", { className: "confirm-title", children: "No confirmation data" }), _jsx("p", { children: "Go back and book an appointment first." }), _jsx("div", { className: "confirm-actions", children: _jsx("button", { className: "btn-primary", onClick: () => nav("/book"), children: "Back to Booking" }) })] }) }));
    }
    return (_jsx("div", { className: "confirm-page", children: _jsxs("div", { className: "confirm-card", children: [_jsx("div", { className: "confirm-title", children: " Appointment Confirmed \u2705" }), _jsxs("div", { className: "confirm-grid", children: [_jsxs("div", { children: [_jsx("div", { className: "k", children: "Doctor" }), _jsx("div", { className: "v", children: data.doctorName })] }), _jsxs("div", { children: [_jsx("div", { className: "k", children: "Clinic" }), _jsx("div", { className: "v", children: data.clinicName })] }), _jsxs("div", { children: [_jsx("div", { className: "k", children: "Speciality" }), _jsx("div", { className: "v", children: data.specialityName })] }), _jsxs("div", { children: [_jsx("div", { className: "k", children: "Date & Time" }), _jsx("div", { className: "v", children: data.when })] }), _jsxs("div", { children: [_jsx("div", { className: "k", children: "Duration" }), _jsxs("div", { className: "v", children: [data.duration, " min"] })] }), _jsxs("div", { children: [_jsx("div", { className: "k", children: "Owner" }), _jsxs("div", { className: "v", children: [data.owner.firstName, " ", data.owner.lastName] })] }), _jsxs("div", { children: [_jsx("div", { className: "k", children: "Contact" }), _jsxs("div", { className: "v", children: [data.owner.email, " \u00B7 ", data.owner.telephone] })] }), _jsxs("div", { className: "span2", children: [_jsx("div", { className: "k", children: "Pet" }), _jsxs("div", { className: "v", children: [data.pet.name || "—", " \u2022 ", data.pet.species || "—", " \u2022 ", data.pet.breed || "—", data.pet.age ? ` • age: ${data.pet.age}` : "", data.pet.notes ? _jsxs(_Fragment, { children: [_jsx("br", {}), data.pet.notes] }) : null] })] })] }), _jsxs("div", { className: "confirm-actions", children: [_jsx("button", { className: "btn-secondary", onClick: () => nav(-1), children: "Back" }), _jsx("button", { className: "btn-primary", onClick: () => nav("/book"), children: "Book Another" })] })] }) }));
}
